<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('products')->delete();

        \DB::table('products')->insert(array(
            0 =>
            array(
                'id' => 1,
                'name' => 'Frutti',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => '12.00',
                'price_pannu' => '13.00',
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:26:05',
                'updated_at' => '2022-08-21 19:42:26',
            ),
            1 =>
            array(
                'id' => 2,
                'name' => 'Romeo',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => '12.40',
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:26:29',
                'updated_at' => '2022-08-21 19:43:07',
            ),
            2 =>
            array(
                'id' => 3,
                'name' => 'Fransescana',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '10.50',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:30:12',
                'updated_at' => '2022-08-17 17:30:12',
            ),
            3 =>
            array(
                'id' => 4,
                'name' => 'Quattro',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:30:47',
                'updated_at' => '2022-08-17 17:30:47',
            ),
            4 =>
            array(
                'id' => 5,
                'name' => 'Spicy Vege',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.30',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:31:06',
                'updated_at' => '2022-08-17 17:31:06',
            ),
            5 =>
            array(
                'id' => 6,
                'name' => 'Salami',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:31:26',
                'updated_at' => '2022-08-17 17:31:26',
            ),
            6 =>
            array(
                'id' => 7,
                'name' => 'Green Day',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.30',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:31:46',
                'updated_at' => '2022-08-17 17:31:46',
            ),
            7 =>
            array(
                'id' => 8,
                'name' => 'Empire',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:32:03',
                'updated_at' => '2022-08-17 17:32:03',
            ),
            8 =>
            array(
                'id' => 9,
                'name' => 'Papa Special',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 1,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 17:32:28',
                'updated_at' => '2022-08-17 17:32:28',
            ),
            9 =>
            array(
                'id' => 10,
                'name' => 'Leipäkebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '10.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:38:25',
                'updated_at' => '2022-08-17 18:38:25',
            ),
            10 =>
            array(
                'id' => 11,
                'name' => 'Iskenderkebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:38:45',
                'updated_at' => '2022-08-17 18:38:45',
            ),
            11 =>
            array(
                'id' => 12,
                'name' => 'Rullakebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:39:02',
                'updated_at' => '2022-08-17 18:39:02',
            ),
            12 =>
            array(
                'id' => 13,
                'name' => 'Kebab Special',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:39:19',
                'updated_at' => '2022-08-17 18:39:19',
            ),
            13 =>
            array(
                'id' => 14,
                'name' => 'Kebab Ranskalaisilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:39:34',
                'updated_at' => '2022-08-17 18:39:34',
            ),
            14 =>
            array(
                'id' => 15,
                'name' => 'Fetarulla Kebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:40:00',
                'updated_at' => '2022-08-17 18:40:00',
            ),
            15 =>
            array(
                'id' => 16,
                'name' => 'Aurarulla Kebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:40:17',
                'updated_at' => '2022-08-17 18:40:17',
            ),
            16 =>
            array(
                'id' => 17,
                'name' => 'Kebab Salaatilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:40:31',
                'updated_at' => '2022-08-17 18:40:31',
            ),
            17 =>
            array(
                'id' => 18,
                'name' => 'Kebab Lohkoperunoilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.30',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 6,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:40:50',
                'updated_at' => '2022-08-17 18:40:50',
            ),
            18 =>
            array(
                'id' => 19,
                'name' => 'Leipäkanakebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '10.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:41:30',
                'updated_at' => '2022-08-17 18:41:30',
            ),
            19 =>
            array(
                'id' => 20,
                'name' => 'Kanakebab Riisillä',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '10.50',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:41:47',
                'updated_at' => '2022-08-17 18:41:47',
            ),
            20 =>
            array(
                'id' => 21,
                'name' => 'Kanakebab Special',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:42:07',
                'updated_at' => '2022-08-17 18:42:07',
            ),
            21 =>
            array(
                'id' => 22,
                'name' => 'Kanakebab Ranskalaisilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:42:22',
                'updated_at' => '2022-08-17 18:42:22',
            ),
            22 =>
            array(
                'id' => 23,
                'name' => 'Kanakebab Lohkoperunoilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.30',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:42:42',
                'updated_at' => '2022-08-17 18:42:42',
            ),
            23 =>
            array(
                'id' => 24,
                'name' => 'Rullattu Kanakebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:42:56',
                'updated_at' => '2022-08-17 18:42:56',
            ),
            24 =>
            array(
                'id' => 25,
                'name' => 'Rullattu Fetakanakebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 18:43:15',
                'updated_at' => '2022-08-17 18:43:15',
            ),
            25 =>
            array(
                'id' => 27,
                'name' => 'Kanakebab Salaatilla',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.00',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 19:04:31',
                'updated_at' => '2022-08-17 19:04:31',
            ),
            26 =>
            array(
                'id' => 28,
                'name' => 'Rullattu Aurakanakebab',
                'description' => NULL,
                'thumbnail' => NULL,
                'price_norm' => '11.40',
                'price_perhe' => NULL,
                'price_pannu' => NULL,
                'menu_id' => 7,
                'restaurant_id' => 5,
                'created_at' => '2022-08-17 19:06:21',
                'updated_at' => '2022-08-17 19:06:21',
            ),
        ));
    }
}